name: react POC CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm run build
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Display message
        run: |
          echo "hello world"
